### ISSUE TITLE
[Bug 🐞]: KD-RecyclerSmall part not fully localized

### ISSUE THREAD

**Issue by ShadowSTARS616** [zer0Kerbal/KeridianDynamics#47]
### Brief description of your issue

Converter name and action name of this part not localized in 
It seems
#KDVA-KDRecyclerSmall-MRC-Rolls_ConverterName
#KDVA-KDRecyclerSmall-MRC-Rolls_StartActionName
#KDVA-KDRecyclerSmall-MRC-Rolls_StopActionName
#KDVA-KDRecyclerSmall_ModuleAnimationGroup_moduleType
have some issues - when I added texts to them, they just not works and outputs `Rolls` `Start Rolls`, etc. 

### Steps to reproduce

0. Install Version 0.8.99.1-prerelease from zip, set language to simplified Chinese
1. Copy en-us.cfg and rename it as zh-cn.cfg
2. find
#KDVA-KDRecyclerSmall-MRC-Rolls_ConverterName
#KDVA-KDRecyclerSmall-MRC-Rolls_StartActionName
#KDVA-KDRecyclerSmall-MRC-Rolls_StopActionName
#KDVA-KDRecyclerSmall_ModuleAnimationGroup_moduleType
and add some localized text behind `=`
3. Run the game

### Expected behavior

Localized text should be displayed in game

### Actual behavior

Text not localized:
![1](https://user-images.githubusercontent.com/102458339/180950645-17442f2e-1aa2-470d-bed6-79523eb7d415.jpg)

### Environment

```shell
Mod:0.8.99.1-prerelease
KSP:1.12.3.3173 with Breaking Ground 1.7.1
Installation: Github 0.8.99.1-prerelease zip and 0.8.99.2-prerelease
```

### How did you download and install this?

GitHub release .zip (advanced manual installation)

**Comment by zer0Kerbal** [comment]
Thank you @ShadowSTARS616 ! excellent bug report.

issue lies in the un-localized text that was left in the part.cfg (my bad) 📛 
WIll be fixed in next version (which I am working on in the next 24-36 hours)
```
		ConverterName = #KDVA-KDRecyclerSmall_ModuleResourceConverter_Rolls_ConverterName	// #KDVA-KDRecyclerSmall_ModuleResourceConverter_Rolls_ConverterName = Toggle Rolls
		StartActionName = #KDVA-KDRecyclerSmall_ModuleResourceConverter_Rolls_StartActionName	// #KDVA-KDRecyclerSmall_ModuleResourceConverter_Rolls_StartActionName = Start Rolls
		StopActionName = #KDVA-KDRecyclerSmall_ModuleResourceConverter_Rolls_StopActionName	// #KDVA-KDRecyclerSmall_ModuleResourceConverter_Rolls_StopActionName = Stop Rolls
		ConverterName = Rolls
		StartActionName = Start Rolls
		StopActionName = Stop Rolls
```
