### ISSUE TITLE
[Bug 🐞]: Cannot equip sledgehammer or stakes

### ISSUE THREAD

**Issue by x13x54** [zer0Kerbal/KeridianDynamics#5]
### Brief description of your issue

Cannot equip sledgehammer part to place survey stakes due to KD using outdated KIS patch.
This also applies to the stakes.

### Steps to reproduce

Get a kerbal on EVA with a sledgehammer in it's KIS inventory.
Try to equip the sledgehammer.

### Expected behavior

Sledgehammer equips.

### Actual behavior

Sledgehammer does not equip.
The following message appears in console:
```
Equip Item: partName=KD-SledgeHammer "Susie", mode=Model
Error: Cannot find object for EVA item: bn_r_mid_a01
```
Because the patch to make the item KIS equipable is from before KSP 1.5 after which something was fundamentally changed as detailed [on the KIS github wiki](https://github.com/ihsoft/KIS/wiki/Equippable-items-in-KIS-v1.15-and-higher)

### Environment

```shell
Mod: latest version from github.
SimpleConstruction: had to use curseforge version since ckan/github version lacked the extraplanetary launchpad DLL. Also had to change the MM patch that would be ran incase EL was missing to run even with it present as the launchpad DLL stopped them from running.
Ksp: latest.
Log: n/a, i foud the root of the issue, described here:
https://github.com/ihsoft/KIS/wiki/Equippable-items-in-KIS-v1.15-and-higher
```

### How did you download and install this?

GitHub release .zip (advanced manual installation)

**Comment by x13x54** [comment]
Also survey stakes are upside down when placed, i do have the option to rotate them but then only the top 1/10th is sticking out from the ground, and when that folds open when you deploy it the stake is basically invisible because it's clipped into the ground.

And i had an issue while trying to use KD along with SimpleConstruction. SC through CKAN does not include the launchpad.dll so i had to use the curseforge version which gave a fatal B9PartSwitch error; basically MetalOre was not defined because SC does not add it and in KD/Resources/Resources.cfg the MM patch that would add MetalOre does not get run because the conditional that checks for EL not being installed does not pass because the EL dll file is present.

Let me know if you want more details on this.

**Comment by zer0Kerbal** [comment]
@x13x54 - thank you - have added KDVA to the short list - it is due for another release.

**Comment by x13x54** [comment]
i can create a pull request with the workaround i came up with for this specific issue if you want. I don't think it'll put the equipped items in the anatomically correct place but at least it will work.

Furthermore, should i create a new issue for the following? i haven't seen it in the issue tracker 
> And i had an issue while trying to use KD along with SimpleConstruction. SC through CKAN does not include the launchpad.dll so i had to use the curseforge version which gave a fatal B9PartSwitch error; basically MetalOre was not defined because SC does not add it and in KD/Resources/Resources.cfg the MM patch that would add MetalOre does not get run because the conditional that checks for EL not being installed does not pass because the EL dll file is present.

**Comment by zer0Kerbal** [comment]
@x13x54 thank you.

Yes please. for both.
