### ISSUE TITLE
[Bug 🐞]: Does not work with SimpleConstruction (W workaround!)

### ISSUE THREAD

**Issue by x13x54** [zer0Kerbal/KeridianDynamics#81]
### Brief description of your issue (aka the problem)

I want to use KD along with SC, but when i install this there are module manager errors, caused by the MetalOre resource not being defined.
KD is supposed to provide these definitions if EL is missing (`KD/Resources/Resources.cfg` line 26, 38), however since the EL folder and DLL are included `!Launchpad` is false, and thus these patches don't get applied.
As a temporary workaround i have removed the `!` in front of `!Launchpad` so these patches get applied and my game starts with no issues

### KSP version

1.12.4

### Version of addon

0.8.99.6-prerelease-CF

### Steps to reproduce the behavior or issue

1. Install SimpleConstruction and KeridianDynamics then start game

### Environment

```shell
KSP: 1.12.4
KeridianDynamics: 0.8.99.6-prerelease-CF
SimpleConstruction: 4.0.99.33-prerelease-CF
```

### How did you download and install this?

CurseForge (download and manual installation)

**Comment by zer0Kerbal** [comment]
they patches shouldn't be applied, but at the same time it shouldn't be causing errors. will address in next release.

**Comment by zer0Kerbal** [comment]
working on a new release @x13x54 

So you have SCON + KDVA and it is asking for MetalOre? I ask because SCON doesn't require MetalOre (rather Metal)
